[libraries]
axion-release-plugin = "pl.allegro.tech.build:axion-release-plugin:1.14.2"
gradle-testsets-plugin = "org.unbroken-dome.gradle-plugins:gradle-testsets-plugin:4.0.0"
junit-jupiter = "org.junit.jupiter:junit-jupiter:5.9.1"
junit-pioneer = "org.junit-pioneer:junit-pioneer:1.9.0"
kotlin-gradle-plugin = "org.jetbrains.kotlin:kotlin-gradle-plugin:1.7.21"
kotlin-allopen = "org.jetbrains.kotlin:kotlin-allopen:1.7.21"
ktlint-gradle = "org.jlleitschuh.gradle:ktlint-gradle:11.0.0"
mockk = "io.mockk:mockk:1.13.2"
releases-hub-gradle-plugin = "com.dipien:releases-hub-gradle-plugin:4.0.0"
sshd-core = "org.apache.sshd:sshd-core:2.9.2"
spring-boot-gradle-plugin = "org.springframework.boot:spring-boot-gradle-plugin:2.7.5"

[bundles]
kotlin = ["kotlin-gradle-plugin", "kotlin-allopen"]
