[libraries]
axion-release-plugin = "pl.allegro.tech.build:axion-release-plugin:1.14.1"
gradle-testsets-plugin = "org.unbroken-dome.gradle-plugins:gradle-testsets-plugin:4.0.0"
junit-jupiter = "org.junit.jupiter:junit-jupiter:5.9.1"
junit-pioneer = "org.junit-pioneer:junit-pioneer:1.7.1"
kotlin-gradle-plugin = "org.jetbrains.kotlin:kotlin-gradle-plugin:1.7.20"
kotlin-allopen = "org.jetbrains.kotlin:kotlin-allopen:1.7.20"
ktlint-gradle = "org.jlleitschuh.gradle:ktlint-gradle:11.0.0"
releases-hub-gradle-plugin = "com.dipien:releases-hub-gradle-plugin:3.1.0"
sshd-core = "org.apache.sshd:sshd-core:2.9.1"
mockk = "io.mockk:mockk:1.13.1"

[bundles]
kotlin = ["kotlin-gradle-plugin", "kotlin-allopen"]
