[libraries]
axion-release-plugin = "pl.allegro.tech.build:axion-release-plugin:1.15.0"
junit-jupiter = "org.junit.jupiter:junit-jupiter:5.9.2"
kotlin-gradle-plugin = "org.jetbrains.kotlin:kotlin-gradle-plugin:1.8.20"
kotlin-allopen = "org.jetbrains.kotlin:kotlin-allopen:1.8.20"
junit-pioneer = "org.junit-pioneer:junit-pioneer:2.0.1"

ktlint-gradle = "org.jlleitschuh.gradle:ktlint-gradle:11.3.1"

mockk = "io.mockk:mockk:1.13.5"

releases-hub-gradle-plugin = "com.dipien:releases-hub-gradle-plugin:4.0.0"
sshd-core = "org.apache.sshd:sshd-core:2.9.2"
spring-boot-gradle-plugin = "org.springframework.boot:spring-boot-gradle-plugin:2.7.5"

[bundles]
kotlin = ["kotlin-gradle-plugin", "kotlin-allopen"]
