name: Upgrade Dependencies
on:
  schedule:
    - cron: "0 0 * * 0,3"
  workflow_dispatch:
    inputs:
      maxPRs:
        description: 'The maximum number of PRs to create during execution'
        required: true
        default: '10'

jobs:
  version-catalog-update:
    name: Update Version Catalog
    uses: projectronin/github/.github/workflows/version_catalog_update.yml@version_catalog_update/v1
    with:
      assignees: "arssycro"